version: '3.8'
services:
  backend:
    build: ./server
    env_file:
      - ./server/.env
    ports:
      - "3001:3001"
    restart: unless-stopped
  frontend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
